---
- hosts: localhost
  become: true
  vars:

  tasks:
    - name: Install yum packages
      yum:
        name:
          - openldap
          - compat-openldap
          - openldap-clients
          - openldap-servers
          - openldap-servers-sql
          - openldap-devel
        state: installed

    - name: Start and enable slapd
      systemd:
        name: slapd
        enabled: yes
        state: started
