---
- hosts: localhost
  become: true
  vars:

  tasks:
    - name: Install yum packages
      yum:
        name:
          - openldap
          - compat-openldap
          - openldap-clients
          - openldap-servers
          - openldap-servers-sql
          - openldap-devel
        state: installed

    - name: Start and enable slapd
      systemd:
        name: slapd
        enabled: yes
        state: started

    - name: Install extra PHP packages
      yum:
        name:
          - php-ldap
          - php-mbstring
          - php-pear
          - php-xml
          - epel-release

    - name: Install yum phpLDAPAdmin
      yum:
        name:
          - phpldapadmin
